Fix unzipping issues and fix exit function usage.
MasterIO02/ordr-client pull request #9
Opened 2022-10-28 13:07 UTC by dragongoose

Duplicate of #8, but with additional changes and for rev19 client.

For unzipping related changes, refer to the body of #8.

The exit function wouldn't stop execution of the script, but sent a exit message and waited for input. 

By calling exit asynchronously, it allows for execution of the script to halt.

Before, this was problematic when exit was called due to an error, but the script would continue and cause more errors.

2022-11-23 18:10 UTC, MasterIO02 commented on files/util.js
> +            zip.extractAllTo(output);
you forgot to add back the unlinkSync

2022-11-23 18:12 UTC, MasterIO02 commented on files/firstLaunch.js
>                          fs.unlinkSync(`${process.cwd()}/files/librespeed-cli/librespeed-cli.zip`)
since we will remove the original zip in the asyncExtract, we don't need to remove it here

2022-11-23 18:14 UTC, MasterIO02 requested changes
plz fix and it should be good

2022-11-26 02:44 UTC, dragongoose commented
Fixed!

2022-11-26 11:47 UTC, merged